# Generated by Django 3.1.7 on 2021-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210706_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
